/**
 * Laundelle Canonical ID Prefixes
 * Every public business identifier is structured as:
 * <PREFIX>-<SECURE_RANDOM_IDENTIFIER>
 */
export const ID_PREFIXES = {
  CUSTOMER: 'CUS',
  STAFF: 'STF',
  ORDER: 'ORD',
  ORDER_ITEM: 'ITM',
  PLANT: 'PLT',
  PAYMENT: 'PAY',
  SUBSCRIPTION: 'SUB',
  INVOICE: 'INV',
  REFUND: 'REF',
  STORE_CREDIT: 'CRD',
  BAG: 'BAG',
  VEHICLE: 'VEH',
  MACHINE: 'MAC',
  MACHINE_RUN: 'RUN',
  PICKUP_ATTEMPT: 'PKA',
  DELIVERY_ATTEMPT: 'DLA',
  COD_RECORD: 'COD',
  INCIDENT: 'INC',
  SUPPORT_TICKET: 'TKT',
  EVIDENCE: 'EV',
  AUDIT_EVENT: 'AUD',
  ADDRESS: 'ADR',
  NOTIFICATION: 'NOT',
  ALERT: 'ALT',
  NOTE: 'NTE',
  FLAG: 'FLG',
  BOOKING_SLOT: 'SLT',
  DEVICE: 'DEV',
  OFFLINE_OPERATION: 'OP',
  VEHICLE_ASSIGNMENT: 'VAS',
  VEHICLE_MAINTENANCE: 'VMT',
  VEHICLE_DOCUMENT: 'DOC',
  INVENTORY_ITEM: 'MAT',
  INVENTORY_TRANSACTION: 'ITX',
  INVENTORY_TRANSFER: 'TRF',
  SERVICE: 'SVC',
  EXCEPTION: 'EXC',
  PRIVACY_REQUEST: 'PRV'
} as const;

export type IdPrefix = (typeof ID_PREFIXES)[keyof typeof ID_PREFIXES];

export const PREFIX_ENTITY_MAP: Record<IdPrefix, string> = {
  CUS: 'Customer',
  STF: 'Staff',
  ORD: 'Order',
  ITM: 'OrderItem',
  PLT: 'Plant',
  PAY: 'Payment',
  SUB: 'Subscription',
  INV: 'Invoice',
  REF: 'Refund',
  CRD: 'StoreCredit',
  BAG: 'Bag',
  VEH: 'Vehicle',
  MAC: 'Machine',
  RUN: 'MachineRun',
  PKA: 'PickupAttempt',
  DLA: 'DeliveryAttempt',
  COD: 'CodRecord',
  INC: 'Incident',
  TKT: 'SupportTicket',
  EV: 'Evidence',
  AUD: 'AuditEvent',
  ADR: 'CustomerAddress',
  NOT: 'Notification',
  ALT: 'UnifiedAlert',
  NTE: 'CustomerNote',
  FLG: 'CustomerFlag',
  SLT: 'BookingSlot',
  DEV: 'RegisteredDevice',
  OP: 'OfflineOperation',
  VAS: 'VehicleAssignment',
  VMT: 'VehicleMaintenance',
  DOC: 'VehicleDocument',
  MAT: 'InventoryItem',
  ITX: 'InventoryTransaction',
  TRF: 'InventoryTransfer',
  SVC: 'Service',
  EXC: 'OperationalException',
  PRV: 'PrivacyRequest'
};
